Help people using statefulsets make better life choices.

diff --git a/src/scripts/generators/generate-kubernetes-workload-statefulset b/src/scripts/generators/generate-kubernetes-workload-statefulset
--- a/src/scripts/generators/generate-kubernetes-workload-statefulset
+++ b/src/scripts/generators/generate-kubernetes-workload-statefulset
@@ -96,6 +96,11 @@ if [[ "${POD_MANAGEMENT_POLICY}" != "OrderedReady" && "${POD_MANAGEMENT_POLICY}"
   exit 4
 fi
 
+if [[ "${POD_MANAGEMENT_POLICY}" == "Parallel" && "${ALLOW_UNRELIABLE_POD_MANAGEMENT_POLICY}" != "I_LIKE_DOWNTIME" ]]; then
+  echo "${LOG_ERROR_PREFIX}Parallel pod management policy can cause data loss and downtime. To use it, set KUBERNETES_STATEFULSET_ALLOW_UNRELIABLE_POD_MANAGEMENT_POLICY=I_LIKE_DOWNTIME${LOG_ERROR_SUFFIX}" >&2
+  exit 4
+fi
+
 if [[ "${UPDATE_STRATEGY_TYPE}" != "RollingUpdate" && "${UPDATE_STRATEGY_TYPE}" != "OnDelete" ]]; then
   echo "${LOG_ERROR_PREFIX}KUBERNETES_STATEFULSET_UPDATE_STRATEGY_TYPE must be 'RollingUpdate' or 'OnDelete', got: ${UPDATE_STRATEGY_TYPE}${LOG_ERROR_SUFFIX}" >&2
   exit 4
